# values-dev.yaml
replicaCount: 1

image:
  tag: "latest"

config:
  appEnv: "dev"
  logLevel: "debug"

mysql:
  primary:
    resourcesPreset: "none"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi
