apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword | quote }}
  API_KEY: {{ .Values.secret.apiKey | quote }}
