name: Helm CI

on:
  push:

jobs:
  helm:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Helm Lint
      run: helm lint .

    - name: Helm Template DEV
      run: helm template my-nginx . -f values-dev.yaml

    - name: Helm Template TEST
      run: helm template my-nginx . -f values-test.yaml

    - name: Helm Template PROD
      run: helm template my-nginx . -f values-prod.yaml
