name: Helm Deployment

on:
  push:

env:
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Image Tag anzeigen
        run: echo "IMAGE_TAG=$IMAGE_TAG"

      - name: Helm prüfen
        run: helm lint .

      - name: Helm Template
        run: |
          helm template my-nginx . \
             -n nginx-lab \
             --set image.tag="$IMAGE_TAG"
