name: Helm CI

on:
  push:

jobs:
  helm:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Helm Lint
        run: helm lint .

      - name: Helm Template DEV
        run: helm template my-nginx . -f values-dev.yaml

      - name: Helm Upgrade DEV
        run: |
          export MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace nginx-lab my-nginx-mysql -o jsonpath="{.data.mysql-root-password}" | base64 -d)
          export MYSQL_PASSWORD=$(kubectl get secret --namespace nginx-lab my-nginx-mysql -o jsonpath="{.data.mysql-password}" | base64 -d)

          helm upgrade --install my-nginx . \
            -n nginx-lab \
            -f values-dev.yaml \
            --set mysql.auth.rootPassword="$MYSQL_ROOT_PASSWORD" \
            --set mysql.auth.password="$MYSQL_PASSWORD"
